{% set name = "mednet" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mednet-{{ version }}.tar.gz
  sha256: b6e48a023f4e698c264be517b80227c1ec21ddf07889c130ffb46ee0cd028bff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - mednet = mednet.scripts.cli:cli

requirements:
  host:
    - python >=3.10
    - hatchling
    - versioningit
    - pip
  run:
    - python >=3.10
    - clapper
    - click
    - credible
    - grad-cam >=1.5.0
    - lightning >=2.2.0
    - h5py
    - matplotlib-base
    - mlflow-skinny
    - numpy
    - pillow
    - psutil
    - python-gitlab
    - scikit-image
    - scikit-learn
    - scipy
    - tabulate
    - tensorboard
    - torchvision >=0.18.0
    - pytorch
    - torchio
    - tqdm
    - versioningit

test:
  source_files:
    - tests
  imports:
    - mednet
  commands:
    - pip check
    - mednet --help
    # minimal testing of this packaging
    - pytest -sv tests/test_cli.py
  requires:
    - pip
    - pytest

about:
  home: https://gitlab.idiap.ch/biosignal/software/mednet
  doc_url: https://mednet.readthedocs.io
  dev_url: https://gitlab.idiap.ch/biosignal/software/mednet
  summary: Computer-Aided Detection and Segmentation from Medical Data
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - anjos
