{% set python_min = '3.10' %}
{% set name = "mednet" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mednet-{{ version }}.tar.gz
  sha256: bb79e70a53b5eaaa8fd9dccd9e1da535a14e40119efdc73ba6b666784e5c0ca3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - mednet = mednet.scripts.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - clapper >=1.3.1
    - click
    - colorlog
    - compact-json
    - credible
    - grad-cam >=1.5.0
    - lightning >=2.2.0
    - h5py
    - matplotlib-base
    - mlflow-skinny
    - numpy
    - pillow
    - psutil
    - python-gitlab
    - scikit-image
    - scikit-learn
    - scipy
    - tabulate
    - tensorboard
    - torchvision >=0.18.0
    - pytorch
    - torchio
    - torchmetrics
    - tqdm
    - versioningit

test:
  source_files:
    - tests
  imports:
    - mednet
  commands:
    - pip check
    - mednet --help
    # minimal testing of this packaging
    - pytest -sv tests/test_cli.py
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://gitlab.idiap.ch/biosignal/software/mednet
  doc_url: https://mednet.readthedocs.io
  dev_url: https://gitlab.idiap.ch/biosignal/software/mednet
  summary: Multi-task Library to Develop Computer-Aided Tools for Medical Data Analysis
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - anjos
