context:
  name: mednet
  version: 2.0.0
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/ec/1a/c77865bc2b5e2ad9d32b11ebad43b81d7bf1280a8da3ed264dad68572779/mednet-${{ version }}.tar.gz
  sha256: 09b2d5553e95068808579ca81f96c514e37124c07be58c508c5f4947178e5703

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mednet = mednet.scripts.cli:cli

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - clapper >=1.3.1
    - click
    - colorlog
    - compact-json
    - credible >=1.0.2
    - grad-cam >=1.5.0
    - lightning >=2.2.0
    - loky
    - h5py
    - matplotlib-base
    - mlflow-skinny
    - numpy
    - peft
    - pillow
    - psutil
    - python-gitlab
    - scikit-image
    - scikit-learn
    - scipy
    - tabulate
    - tensorboard
    - timm
    - torchvision >=0.18.0
    - pytorch
    - torchio
    - torchmetrics
    - tqdm
    - versioningit

tests:
  - python:
      imports:
        - mednet
      pip_check: true
      python_version: ${{ python_min }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - pip
        - pytest
    script:
      - mednet --help
      - pytest --override-ini pythonpath=tests/src -sv tests/cli/test_cli.py

about:
  summary: Multi-task Library to Develop Computer-Aided Tools for Medical Data Analysis
  license: GPL-3.0-or-later
  license_file: LICENSES/GPL-3.0-or-later.txt
  homepage: https://gitlab.idiap.ch/biosignal/software/mednet
  repository: https://gitlab.idiap.ch/biosignal/software/mednet
  documentation: https://mednet.readthedocs.io

extra:
  recipe-maintainers:
    - anjos
